name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        run: |
          choco install graalvm --version=22.3.0 # Specify the version you need
          echo "GRAALVM_HOME=C:\ProgramData\chocolatey\lib\graalvm\tools\graalvm" >> $GITHUB_ENV
          echo "PATH=$GRAALVM_HOME\bin;$PATH" >> $GITHUB_ENV

      - name: Verify GRAALVM_HOME
        run: echo $env:GRAALVM_HOME

      - name: List GraalVM bin directory
        run: dir "$env:GRAALVM_HOME\bin"

      - name: Install Native Image
        shell: pwsh
        run: |
          & "$env:GRAALVM_HOME\bin\gu" install native-image

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Specify your Java version
          distribution: 'graalvm'

      - name: Build Java Application with Maven
        run: mvn clean package

      - name: Create Native Image
        run: |
          native-image -cp target/classes de.tkunkel.omd.overlay.starter.Starter

      - name: Upload Executable
        uses: actions/upload-pages-artifact@v3
        with:
          name: myapp-executable
          path: Starter.exe # Change this to the name of your executable
