name: Build Java Application with GraalVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Specify your Java version
          distribution: 'graalvm'

      - name: Install Native Image
        run: gu install native-image

      - name: Build Java Application
        run: |
          mkdir -p out
          javac -d out src/main/java/de/tkunkel/omd/overlay/starter/Starter.java

      - name: Create Native Image
        run: |
          native-image -cp out de.tkunkel.omd.overlay.starter.Starter

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: myapp-executable
          path: Starter.exe # Change this to the name of your executable
